const support = 'aloe.vera225@yahoo.com';
const name = 'Valentyn Shemeiko';
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const operator = escape(name);
const email = escape(support);
const pages = {
  '/privacy': ['Privacy Policy', `
    <p>Effective 29 September 2026. NOW is operated by ${operator}, Norway. Privacy requests: <a href="mailto:${email}">${email}</a>.</p>
    <h2>Information we process</h2><p>When you register, we store your email, display name, password hash, profile and settings. Listings, applications, messages, reviews, reports and blocks contain information you choose to submit. We process your approximate or precise location only when you grant access or enter a location. We use session tokens to keep you signed in and basic request data to prevent abuse. NOW sends text entered in the AI request feature to OpenAI for processing. Public listings, profiles, community posts and reviews are also sent to OpenAI for automated content safety checks before publication. External opportunity links may take you to other sites with their own policies.</p>
    <h2>Why and with whom</h2><p>We use this data to provide accounts, search, nearby results, chats, transactions between users, moderation and security. We host the service and database on Railway and use OpenAI for requests to the AI feature. We do not sell your personal data. Other users can see your public profile, active listings and the content you send them. Your precise coordinates are used for nearby matching and may be included in a listing you publish; avoid sharing a sensitive home location.</p>
    <h2>Control and deletion</h2><p>You can turn off location permission in your device or browser. In the app, open YOU → Delete account to delete your account. This removes your profile identifiers and public listings, deletes your direct conversations and community posts, removes your authored reviews and redacts your messages and deal details. Anonymized job records may remain to preserve the other participant's history. To request access, correction or deletion, email <a href="mailto:${email}">${email}</a>. See <a href="/delete-account">account deletion</a>.</p>
    <h2>Retention and rights</h2><p>Active data is kept while your account is in use. Deleted content is removed from the live database as described above; one-way purchase identifiers may remain to prevent repeated redemption. Backups may persist for a limited period under the hosting provider's backup schedule. We may retain information where required for legal obligations or dispute handling. You may request access, correction, erasure, restriction or a copy of your data by email, and complain to your local data protection authority.</p>
    <h2>Store purchases and advertising</h2><p>In the installed store versions, optional NOW Plus, NOW Business and Boost purchases use Apple App Store or Google Play billing. RevenueCat receives a NOW account identifier and purchase and subscription records so we can verify access, renewals and restoration. We do not receive your full card details. Free accounts may see Google AdMob ads after its consent flow permits them. AdMob may process device identifiers and usage data according to the choices you make in that flow; advertising privacy choices are available in Settings when ads are enabled. NOW Plus and Business do not show ads. These services are disabled in the web version until configured for the store release.</p>`],
  '/terms': ['Terms of Use', `
    <p>Effective 29 September 2026. NOW is operated by ${operator}, Norway. Contact <a href="mailto:${email}">${email}</a>.</p>
    <h2>Using NOW</h2><p>NOW helps people discover opportunities, exchange listings, arrange work and communicate. You must provide accurate information, comply with applicable law and respect other users. Do not post scams, illegal goods or services, threats, harassment, impersonation or misleading listings. You are responsible for your interactions, including safety, price, tax and any agreement made with another user. NOW does not itself employ users, arrange transport, hold funds or guarantee an outcome.</p>
    <h2>Content and safety</h2><p>You retain responsibility for your content and grant NOW permission to display and process it to operate the service. Report suspicious listings from the listing details. You can block users. We may remove content or restrict accounts when needed for safety or misuse. Contact <a href="mailto:${email}">${email}</a> to appeal a moderation decision.</p>
    <h2>Paid features</h2><p>NOW Plus and NOW Business are monthly subscriptions; Boost is a one-time purchase applied to one listing for 72 hours. Purchase controls are enabled only when the applicable store payment flow and verification are configured. The store shows the final local price, renewal and cancellation terms before purchase. Cancel a subscription through your Apple or Google account; access continues until its paid period expires. Refunds follow the applicable store's process and law. Free referral credits may be used without a purchase.</p>
    <h2>Accounts</h2><p>Keep your sign-in details secure. You may delete your account in YOU → Delete account; see <a href="/delete-account">details</a>. NOW may update these terms and display a new effective date. If you have questions, contact <a href="mailto:${email}">${email}</a>.</p>`],
  '/support': ['NOW Support', `<p>For help, safety reports, privacy requests and purchase questions, email <a href="mailto:${email}">${email}</a>.</p><p>Include a description of the issue and the email tied to your account. Never send a password or verification code.</p><p><a href="/delete-account">How to delete an account</a> · <a href="/privacy">Privacy Policy</a> · <a href="/terms">Terms</a></p>`],
  '/delete-account': ['Delete your NOW account', `<p>In NOW, sign in, open <strong>YOU</strong>, scroll to <strong>Delete account</strong>, and confirm. Deletion takes effect in the live database immediately and signs you out. Deleting a NOW account does not cancel an Apple or Google subscription; cancel it in your store account first to stop renewal.</p><p>Your account identifiers, public listings, direct conversations and community posts are removed. Authored reviews are deleted; messages and deal details in shared job histories are redacted. Other participants retain anonymized deal records. One-way purchase identifiers may be kept to prevent repeated redemption and store records remain with the store and payment processor. Backups may persist for a limited period under the hosting provider's backup schedule.</p><p>If you cannot sign in, email <a href="mailto:${email}">${email}</a> from the address used for the account to request deletion. We may ask you to verify ownership. Questions about retained information can be sent to the same address.</p>`]
};
function renderLegal(path) {
  const [title, body] = pages[path];
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · NOW</title><style>body{font:16px/1.65 system-ui;max-width:760px;margin:40px auto;padding:0 20px;background:#0b0c10;color:#f7f7fa}a{color:#ac96ff}h1,h2{line-height:1.25}</style><main><h1>${title}</h1>${body}<p><a href="/">← NOW</a></p></main></html>`;
}
module.exports = {pages, renderLegal};
